---
- name: PACKAGE | Install package(s) in {{ ansible_facts['distribution'] }}
  ansible.builtin.yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
  with_items: "{{ package_list }}"
  when: package_list != "{}"
