---
- name: PACKAGE | Dpkg configure in {{ ansible_facts['distribution'] }}
  ansible.builtin.command: dpkg --configure -a
  changed_when: false

- name: PACKAGE | Add stable repository in {{ ansible_facts['distribution'] }}
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ apt_repositories }}"
  when: apt_repositories != "{}"

- name: PACKAGE | Install package(s) in {{ ansible_facts['distribution'] }}
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default(package_state) }}"
    update_cache: "{{ package_update_cache }}"
    cache_valid_time: "{{ package_cache_valid_time }}"
  with_items: "{{ package_list }}"
  when: package_list != "{}"
